version: "2.1"
services:
  mongo:
    restart: unless-stopped
    image: healthcheck/mongo:latest
    environment:
      MONGO_PORT_27017_TCP_PORT: 27017
      JAVA_OPTS: ""
    ports: ["27017:27017"]
    volumes: ["mongo-data:/data/db"]
    networks: [backing-services]
  mongo-express:
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    image: mongo-express:0.42.2
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: guest
      ME_CONFIG_BASICAUTH_PASSWORD: guest
    ports: ["8002:8081"]
    networks: [backing-services]
volumes:
  mongo-data: {}
networks:
  backing-services:
    driver: bridge
